workflows:
  build-android:
    name: Build Paiement Frais
    environment:
      flutter: stable
      vars:
        PROJECT_PATH: .
    scripts:
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
